import logoSrc from "@/assets/logo.png";

interface CourseReport {
  courseId: number;
  title: string;
  instructorName: string;
  collegeName: string;
  price: number;
  studentCount: number;
  totalRevenue: number;
}

interface InvoiceTemplateProps {
  reports: CourseReport[];
  totals: {
    totalRevenue: number;
    totalStudents: number;
    totalCourses: number;
  };
  instructorName: string;
  showAll: boolean;
}

export function InvoiceTemplate({ reports, totals, instructorName, showAll }: InvoiceTemplateProps) {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="invoice-page" data-testid="invoice-template">
      <div className="invoice-header">
        <div className="invoice-logo-section">
          <img src={logoSrc} alt="Noqtaa Academy" className="invoice-logo" />
          <div>
            <h1 className="invoice-title">Noqtaa Academy</h1>
            <p className="invoice-subtitle">Financial Report</p>
          </div>
        </div>
        <div className="invoice-date-section">
          <p className="invoice-date-label">Date</p>
          <p className="invoice-date-value">{today}</p>
          {!showAll && instructorName && (
            <>
              <p className="invoice-date-label" style={{ marginTop: "8px" }}>Instructor</p>
              <p className="invoice-date-value">{instructorName}</p>
            </>
          )}
        </div>
      </div>

      <div className="invoice-divider" />

      <h2 className="invoice-section-title">
        {showAll ? "Platform Revenue Summary" : `Revenue Report - ${instructorName}`}
      </h2>

      <table className="invoice-table">
        <thead>
          <tr>
            <th className="invoice-th invoice-th-left">Course</th>
            <th className="invoice-th invoice-th-right">Students</th>
            <th className="invoice-th invoice-th-right">Price</th>
            <th className="invoice-th invoice-th-right">Total</th>
          </tr>
        </thead>
        <tbody>
          {reports.map((r) => (
            <tr key={r.courseId}>
              <td className="invoice-td invoice-td-left">{r.title}</td>
              <td className="invoice-td invoice-td-right">{r.studentCount}</td>
              <td className="invoice-td invoice-td-right">${r.price.toLocaleString()}</td>
              <td className="invoice-td invoice-td-right">${r.totalRevenue.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr className="invoice-total-row">
            <td className="invoice-td invoice-td-left invoice-td-bold">
              Total ({totals.totalCourses} courses)
            </td>
            <td className="invoice-td invoice-td-right invoice-td-bold">{totals.totalStudents}</td>
            <td className="invoice-td invoice-td-right"></td>
            <td className="invoice-td invoice-td-right invoice-td-bold">${totals.totalRevenue.toLocaleString()}</td>
          </tr>
        </tfoot>
      </table>

      <div className="invoice-signatures">
        <div className="invoice-signature-block">
          <div className="invoice-signature-line"></div>
          <p className="invoice-signature-label">Accountant Signature</p>
        </div>
        <div className="invoice-signature-block">
          <div className="invoice-signature-line"></div>
          <p className="invoice-signature-label">Manager Signature</p>
        </div>
      </div>

      <div className="invoice-footer-text">
        <p>This document is generated by Noqtaa Academy financial system.</p>
        <p>Generated on {today}</p>
      </div>
    </div>
  );
}
